# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ls
      - name: uploading the index.htlm
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: index.html

  build2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Download the index.html
        uses: actions/download-artifact@v2
        with:
          name: index.html
          
      - run: ls
          

      
      
